name: Build Thesis PDF

on:
  push:
    tags:
      - "thesis-v*" # Trigger on thesis version tags like thesis-v1.0.0, thesis-v2.1.3, etc.

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile thesis
        uses: xu-cheng/texlive-action@v3
        with:
          run: |
            chmod +x compile.sh
            ./compile.sh

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: thesis-pdf-${{ github.ref_name }}
          path: main.pdf
